export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/register',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    REFRESH: '/auth/refresh',
  },
  USERS: {
    LIST: '/users',
    GET: (id: string) => `/users/${id}`,
    CREATE: '/users',
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
  },
  PRODUCTS: {
    LIST: '/products',
    GET: (id: string) => `/products/${id}`,
    CREATE: '/products',
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
  },
  CART: {
    GET: '/cart/user',
    ADD: (id: string) => `/cart/${id}/items`,
    UPDATE: (id: string, itemId: string) => `/cart/${id}/items/${itemId}`,
    DELETE: (id: string, itemId: string) => `/cart/${id}/items/${itemId}`,
  },
  ORDERS: {
    ALL: '/orders/all',
    MY_ORDERS: '/orders',
    BY_SHOP: (shopId: string) => `/orders/shop/${shopId}`,
    CREATE: '/orders',
    GET: (id: string) => `/orders/${id}`,
    UPDATE: (id: string) => `/orders/${id}`,
    DELETE: (id: string) => `/orders/${id}`,
    CONFIRM: (id: string) => `/orders/${id}/confirm`,
  },
  CHAT: {
    CONVERSATIONS: '/chat/conversations',
    CONVERSATION_DETAIL: (id: string) => `/chat/conversations/${id}`,
    CONVERSATION_MESSAGES: (id: string) => `/chat/conversations/${id}/messages`,
    MARK_AS_READ: (id: string) => `/chat/conversations/${id}/read`,
    CLOSE: (id: string) => `/chat/conversations/${id}/close`,
    RESOLVE: (id: string) => `/chat/conversations/${id}/resolve`,
    SHOP_CONVERSATIONS: (shopId: string) => `/chat/shop/${shopId}/conversations`,
    MESSAGE: (id: string) => `/chat/messages/${id}`,
  },
  SHOPS: {
    TOP_RATED: '/shops/top-rated/list',
    LIST: '/shops',
    GET_BY_USER_ID: '/shops/owner/me',
    GET: (id: string) => `/shops/${id}`,
    GET_PRODUCTS: (id: string) => `/shops/${id}/products`,
    CREATE: '/shops',
    UPDATE: (id: string) => `/shops/${id}`,
    DELETE: (id: string) => `/shops/${id}`,
  },
  VOUCHERS: {
    ALL: '/vouchers',
    GET: (id: string) => `/vouchers/${id}`,
    GET_BY_CODE: (code: string) => `/vouchers/code/${code}`,
    PUBLIC: '/vouchers/customer/public',
    SHOP: (shopId: string) => `/vouchers/shop/${shopId}`,
    CREATE: '/vouchers',
  },
  ANALYTICS: {
    REVENUE: '/analytics/revenue',
    REVENUE_TREND: '/analytics/revenue-trend',
    ORDERS: '/analytics/orders',
    ORDERS_TREND: '/analytics/orders-trend',
    COMPREHENSIVE: '/analytics/comprehensive',
    REAL_TIME: '/analytics/real-time',
    PAYMENT: '/analytics/payment',
    PRODUCTS: '/analytics/products',
    TOP_SHOPS: '/analytics/top-shops',
    SHOP_ANALYTICS: (shopId: string) => `/shops/${shopId}/analytics`,
  },
} as const
